class ExponentError(Exception):
    pass


class HandledExponentError(Exception):
    pass
