pyoso/__init__.py,sha256=pGcyBcTF0baurv-yj-c3XgSkKX1dWkClFqvPT7snbKE,195
pyoso/client.py,sha256=Doh1TCTu1y41kfNHxV8L-Xn-60XrXvPH8yKjqvA1b5Y,1678
pyoso/exceptions.py,sha256=3S9gY6ndSmAENPPVYeY4tI6yyx91dngF0owZUykJUUM,278
pyoso/utils.py,sha256=-4Glpr8Rymv7jnNZQSkx9KjCVV5XMC83og0C1iLsjoU,372
pyoso-0.1.4.dist-info/METADATA,sha256=lYVFm9960PAXinHYTHlCYl3OoFDc1jPxpAcHN3PmOuY,1130
pyoso-0.1.4.dist-info/WHEEL,sha256=In9FTNxeP60KnTkGw7wk6mJPYd_dQSjEZmXdBdMCI-8,91
pyoso-0.1.4.dist-info/top_level.txt,sha256=xKfiZHJRt0V88DxPF1o_MOL27K5GTngL94ORwalzi6A,6
pyoso-0.1.4.dist-info/RECORD,,
